# Generated by Django 4.0 on 2021-12-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.FloatField()),
                ('n', models.FloatField()),
                ('e', models.FloatField()),
                ('s', models.FloatField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
